# Generated by Django 2.2.24 on 2022-10-07 11:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('galaxy', '0001_initial'),
        ('gfiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Workflow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workflowjson', models.TextField(max_length=5000)),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200)),
                ('galaxy_id', models.CharField(max_length=200)),
                ('latest_workflow_uuid', models.CharField(max_length=200)),
                ('accessible', models.BooleanField(default=True)),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('galaxyinstancetracking', models.ForeignKey(help_text='The galaxy instance the Workflow should currently be performed on', null=True, on_delete=django.db.models.deletion.CASCADE, to='galaxy.GalaxyInstanceTracking')),
            ],
        ),
        migrations.CreateModel(
            name='WorkflowRun',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rundate', models.DateTimeField(auto_now_add=True)),
                ('library', models.BooleanField(help_text='Use files from data library')),
                ('history_name', models.CharField(max_length=200)),
                ('ran_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='galaxy.Workflow')),
            ],
        ),
        migrations.CreateModel(
            name='WorkflowInput',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('step', models.CharField(max_length=200)),
                ('datatype', models.CharField(max_length=200)),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='galaxy.Workflow')),
            ],
        ),
        migrations.CreateModel(
            name='HistoryData',
            fields=[
                ('genericfile_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='gfiles.GenericFile')),
                ('name', models.CharField(max_length=200)),
                ('history', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='galaxy.History')),
            ],
            bases=('gfiles.genericfile',),
        ),
        migrations.AddField(
            model_name='history',
            name='galaxyinstancetracking',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='galaxy.GalaxyInstanceTracking'),
        ),
        migrations.AddField(
            model_name='genericfilestogalaxyhistoryparam',
            name='added_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='genericfilestogalaxyhistoryparam',
            name='galaxyinstancetracking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='galaxy.GalaxyInstanceTracking'),
        ),
        migrations.AddField(
            model_name='galaxyuser',
            name='galaxyinstancetracking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='galaxy.GalaxyInstanceTracking'),
        ),
        migrations.AddField(
            model_name='galaxyuser',
            name='internal_user',
            field=models.ForeignKey(help_text='The internal user for the Django (MOGI) web application. i.e. the User from this web application that is linking to the Galaxy user', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='galaxyinstancetracking',
            name='owner',
            field=models.ForeignKey(blank=True, help_text='The user who created the link with this Galaxy instance', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='galaxyfilelink',
            name='galaxyinstancetracking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='galaxy.GalaxyInstanceTracking'),
        ),
        migrations.AddField(
            model_name='galaxyfilelink',
            name='genericfile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gfiles.GenericFile'),
        ),
        migrations.AddField(
            model_name='filestogalaxydatalibraryparam',
            name='added_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='filestogalaxydatalibraryparam',
            name='galaxyinstancetracking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='galaxy.GalaxyInstanceTracking'),
        ),
        migrations.AlterUniqueTogether(
            name='history',
            unique_together={('galaxyinstancetracking', 'galaxy_id')},
        ),
        migrations.AlterUniqueTogether(
            name='galaxyuser',
            unique_together={('internal_user', 'galaxyinstancetracking')},
        ),
        migrations.AlterUniqueTogether(
            name='galaxyfilelink',
            unique_together={('galaxyinstancetracking', 'galaxy_id')},
        ),
    ]
