# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-30 14:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galaxy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='galaxyinstancetracking',
            name='galaxy_root_path',
            field=models.CharField(blank=True, help_text='If the Galaxy instance is accessibleeither via a symlink or directly, the path should be included here', max_length=500, null=True),
        ),
    ]
